FROM tensorflow/tensorflow:1.4.1-devel-py3
LABEL maintainer="jc.jimenez@microsoft.com"
USER root

RUN apt-get update -y --fix-missing
RUN apt-get install -y --fix-missing \
    curl \
    git \
    libopencv-dev python-opencv \
    vim

RUN pip3 install 'keras>=2.1.3' 
RUN pip3 install --user --upgrade git+https://github.com/broadinstitute/keras-resnet
RUN pip3 opencv-python 
RUN pip3 azure-storage azure-servicebus python-dotenv pandas 
RUN pip3 pillow h5py

ADD ./ /vott-train
WORKDIR /vott-train

CMD git submodule init && git submodule update

CMD python3 traind.py
